# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
defaults: &defaults
  adapter: postgresql
  database: fantasysports
  host: localhost
  username: fantasysports
  password: F4n7a5y
  pool: 16

development:
  <<: *defaults

staging:
  <<: *defaults
  host: '54.213.15.243'

test:
  <<: *defaults
  database: fantasysports_test

production:
  <<: *defaults
  host: fantasysports-postgres-master.clvfjvvzcbre.us-west-2.rds.amazonaws.com
