# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
defaults: &defaults
  adapter: postgresql
  database: fantasysports
  host: localhost
  username: fantasysports
  password: F4n7a5y

development:
  <<: *defaults

staging:
  <<: *defaults

test:
  <<: *defaults
  database: fantasysports_test

production:
  <<: *defaults
  host: '54.213.46.254' # AWS elastic IP pointed to prod db
