test: &default

  # Credentials for REST APIs
  client_id: ASYjhRAYJC03x6xFBRxNtcKzEFInbcY5s3ckd8jR0sukBEf8ghuM_2BNpAeQ
  client_secret: EGxtJBDJUKKVl8HJcV1sjAgZGO-nTpr1fxOXh9i0zaskdAbagqjmB3sCXCtx

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  client_id: AakBYhDA_snCU2434TT4sVNX8FIYlF8DkafbybNXoUirxnzTJ0mih_p6hXqs
  client_secret: EPxXSRCVIPxJIQfSwWCZ9Y1NbN8G9ORUEvh8ng5NyYhhv3BMyB_s_6u3yNUz

  mode: live
  app_id: APP-5TW068719E839182L
