test: &default
  # Credentials for REST APIs
  client_id: ASYjhRAYJC03x6xFBRxNtcKzEFInbcY5s3ckd8jR0sukBEf8ghuM_2BNpAeQ
  client_secret: EGxtJBDJUKKVl8HJcV1sjAgZGO-nTpr1fxOXh9i0zaskdAbagqjmB3sCXCtx

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: bpilch-facilitator_api1.hotmail.com
  password: 1382278375
  signature: AiPC9BjkCyDFQXbSkoZcgqH3hpacAlB-UNWt9X1qnkIsadAo74Hh0vXU
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: bpilch-facilitator@hotmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
  client_id: AakBYhDA_snCU2434TT4sVNX8FIYlF8DkafbybNXoUirxnzTJ0mih_p6hXqs
  client_secret: EPxXSRCVIPxJIQfSwWCZ9Y1NbN8G9ORUEvh8ng5NyYhhv3BMyB_s_6u3yNUz

  mode: live
  app_id: APP-5TW068719E839182L
  username: bpilch_api1.hotmail.com
  password: WLUSM84YEPPTYSLE
  signature: AAHTJWWeDYU10kKlYWyFuvV3a99dA4Tvf.poQi05XeuL5mumCXwijqTA
