
schedule_fetcher:
  cron: "0 11 * * *"
  class: "MLBAllScheduleFetcherWorker"
  queue: mlb_all_schedule_fetcher

teams_fetcher:
  cron: "15 11 * * *"
  class: "MLBTeamsFetcherWorker"
  queue: mlb_teams_fetcher

unfetched_games_worker:
  cron: "0 * * * *"
  class: "UnfetchedGamesWorker"
  queue: unfetched_games_worker
