:concurrency: 5
:verbose: false
:queues:
  - [weekly_digest, 1]
  - [mlb_teams_fetcher, 1]
  - [players_fetcher, 1]
  - [daily_schedule_fetcher, 1]
staging:
  :concurrency: 10
production:
  :concurrency: 25